<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap 5 Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="container-fluid p-5 bg-primary text-white text-center">
  <h1>Read Your Book</h1> 
</div>
  
<div class="container mt-5">
  <div class="row">
    <div class="col-sm-6">
    <?php 
    echo '<img src="http://covers.openlibrary.org/b/olid/'.$look['image'].'-L.jpg" style="width:400px; height:80%;">';
?> 
    </div>
    <div class="col-sm-6">
    <form action="/curl/google" method="post">
    <?php
    if(isset($_POST['title'])){
    echo '<h2 style="color:royalblue"><input type="hidden" name = "title" value ="'.$look['title'].'">TITLE: '.$look['title'].'</h2>';
    }
    echo'<br>';
    if(isset($_POST['publish'])){
    echo '<h2 style="color:royalblue"><input type="hidden" name = "publish" value ="'.$look['publish'].'">PUBLISHING DATE: '.$look['publish'].'</h2>';
    }
    echo'<br>';
    if(isset($_POST['page'])){
    echo '<h2 style="color:royalblue"><input type="hidden" name = "page" value ="'.$look['pages'].'">TOTAL PAGE: '.$look['pages'].'</h2>';
    }
    echo'<br>';
    if(isset($_POST['isbn'])){
    echo '<h2 style="color:royalblue"><input type="hidden" name = "isbn" value ="'.$look['isbn'].'">ISBN: '.$look['isbn'].'</h2>';
    }
    echo'<br>';
    if(isset($_POST['author'])){
    echo '<h2 style="color:royalblue"><input type="hidden" name = "author" value ="'.$look['author'].'">AUTHOR: '.$look['author'].'</h2>';
    }
    echo'<br>';
    if(isset($_POST['google_id']))
    {
    echo '<input type="hidden" name = "google_id" value ="'.$look['google_id'].'">';
    }
    echo "<h3 style='color:rgb(204, 85, 0)'>Description: </h3>";
                echo "<p>An approved textbook at Hogwarts School of Witchcraft and Wizardry since publication, Newt Scamander's masterpiece has entertained wizarding families through the generations. Fantastic Beasts and Where to Find Them is an indispensable introduction to the magical beasts of the wizarding world.</p>";
    ?>
    <input type="submit" name = "search" value="Check on google" style="background-color:rgb(0, 255, 255); border-radius:50px;">
    </form>
    </div>
 </div>
</div>
</body>
</html>