<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php echo $this->tag->form("curl/books"); ?>
    <p>
    <label for="serach">Search</label>
    <?php echo $this->tag->textField("search"); ?>
    </p>
    <p>
        <?php echo $this->tag->submitButton("Search here!"); ?>
    </p>

</form>
</body>
</html>